#!/bin/sh

#
# bkm - bookmark manager
#

# All is well and safe
# shellcheck disable=2154,2048,2086

log() {
    printf '%s\n' "$@"
}

die() {
    log "$1"
    exit 1
}

is_url() {
    printf '%s' "$1" | grep -q -e "http://" -e "https://" -e "www." && {
        return 0
    }

    return 1
}

has_value() {
    [ -z "$1" ] && die "Argument $2 is required"
}

truncate() {
    set -f

    set -- $*

    printf '%s\n' "$*"

    set +f
}

trim() {
    printf '%s\n' "$1" | sed -e "s/ //g"
}

replace() {
    printf '%s\n' "$1" | sed -e "s/ /_/g"
}

sanitize() {
    str=$1
    str=$(truncate "$str")

    if is_url "$str"; then
        str=$(trim "$str")
    else
        str=$(replace "$str")
    fi

    printf '%s\n' "$str"
}

handle_existing() {
    if [ -f "$current" ]; then
        seen=0

        while IFS='=' read -r n u; do
            [ "$name" = "$n" ] && seen=1

            [ "$url" = "$u" ] && {
                log "A bookmark with this URL already exists in the category" \
                    "Category: $category" \
                    "Name: $name" \
                    "URL: $url"

                exit
            }
        done < "$current"

        [ "$seen" -eq 1 ] && {
            log "A bookmark with this name already exists in the category" \
                "Category: $category" \
                "Name: $name" \
                "URL: $url"

            printf '\nEnter new name to save (or press Ctrl+C to abort): '

            read -r "new"

            [ -n "$new" ] && {
                name=$(sanitize "$new")
                handle_existing
                unset new
            }
        }

    else
        :> "$current"
    fi

}

bkm_add() {
    has_value "$name" "-n <name>"
    has_value "$url" "-u <url>"

    is_url "$url" || die "Argument -u <url> arg must be a valid url"

    handle_existing

    printf '%s %s\n' "$name" "$url" >> "$current" || {
        die "Failed to write bookmark to $current"
    }

    log "Bookmark added" \
        "Category: $category" \
        "Name: $name" \
        "URL: $url"
}

bkm_edit() {
    printf 'TODO\n'
}

bkm_open() {
    printf 'TODO\n'
}

bkm_list() {
    printf 'TODO\n'
}

bkm_delete() {
    printf 'TODO\n'
}

help() {

    log "bkm is a simple bookmark manager that uses plain text files to" \
        "store bookmarks under categories in a user-specified directory." \
        "The directory is defined by BKM_DIR in \$SHELL's startup file." "" \
        "Usage: bkm [action] [args]" \
        "Actions:" "" \
        "add -c <category> -n <name> -u <url>" \
        "    Add a new bookmark" "" \
        "edit -c <category> -n <name>" \
        "    Edit a bookmark" "" \
        "open -c <category> -n <name>" \
        "    Open bookmark in \$BROWSER" "" \
        "list -c <category>" \
        "    List all bookmarks in a category" "" \
        "list" \
        "    List all bookmarks by category" "" \
        "delete -c <category> -n <name>" \
        "    Delete a bookmark in a category" "" \
        "delete -c <category>" \
        "    Delete category and all its bookmarks" ""

    exit
}

args() {
    while getopts :c:n:u: opt;
        do case $opt in
            c) category=$(sanitize "$OPTARG") ;;
            n) name=$(sanitize "$OPTARG") ;;
            u) url=$(sanitize "$OPTARG") ;; # just to be safe as typos do occur.
            \?) help ;;
            :) printf 'Option -%s requires an argument\n' "$OPTARG" >&2; exit 1 ;;
            *) printf 'Option -%s does not exist\n' "$OPTARG" >&2; exit 1 ;;
        esac;
    done
}

main() {
    [ -z "$BKM_DIR" ] && die "BKM_DIR is not set"

    mkdir -p "$BKM_DIR"

    action="$1"

    shift

    args "$@"

    case $action in
        add) add=1 ;;
        edit) edit=1 ;;
        open) open=1 ;;
        list) list=1 ;;
        delete) delete=1 ;;
        *) help ;;
    esac

    [ -z "$list" ] && [ -z "$category" ] && die "Arg -c <category> is required"

    current="$BKM_DIR/$category"

    #
    # using a massive if statement is perhaps
    # not the prettiest solution, but it'll do
    # for now.
    #
    if [ -n "$add" ]; then
        bkm_add
    elif [ -n "$edit" ]; then
        bkm_edit
    elif [ -n "$open" ]; then
        bkm_open
    elif [ -n "$list" ]; then
        bkm_list
    elif [ -n "$delete" ]; then
        bkm_delete
    else
        help
    fi
}

main "$@"
